# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lessons.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rlessons.proto\"%\n\twednesday\x12\x18\n\x07lessons\x18\x01 \x03(\x0b\x32\x07.lesson\"g\n\x06lesson\x12\x0e\n\x06lesson\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x10\n\x08\x61udience\x18\x03 \x01(\t\x12\r\n\x05place\x18\x04 \x01(\t\x12\x0f\n\x07teacher\x18\x05 \x01(\t\x12\r\n\x05weeks\x18\x06 \x01(\t\".\n\x04root\x12\r\n\x05group\x18\x01 \x01(\t\x12\x17\n\x03\x64\x61y\x18\x02 \x01(\x0b\x32\n.wednesdayb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lessons_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEDNESDAY._serialized_start=17
  _WEDNESDAY._serialized_end=54
  _LESSON._serialized_start=56
  _LESSON._serialized_end=159
  _ROOT._serialized_start=161
  _ROOT._serialized_end=207
# @@protoc_insertion_point(module_scope)
