package utils.validators;

import java.lang.annotation.*;

/**
 * Annotation for auto generated fields
 */
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
@Documented
public @interface AutoGenerated {
}
