package utils.validators;

public class AutoGenerated1 implements Validatable{
    private static AutoGenerated1 instance;

    public <T> boolean validate(T value) {
        return true;
    }

    @Override
    public Validatable getInstanc() {
        return null;
    }

    public static AutoGenerated1 getInstance() {
        if(instance == null) {
            instance = new AutoGenerated1();
        }
        return instance;
    }
}
